#!/bin/bash
echo "======================================================================"
echo " SummerSplash Web App - Quick Start"
echo "======================================================================"
echo ""
echo "Before running, update appsettings.json with your SQL credentials:"
echo "  File: appsettings.json"
echo "  Change: YOUR_USERNAME and YOUR_PASSWORD"
echo ""
echo "Then run:"
echo "  dotnet run"
echo ""
echo "Access the app at: http://localhost:5000"
echo ""
echo "======================================================================"
